name: Covid19CasesCounterApp
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  url_launcher:
  shared_preferences:
  http:
  dynamic_theme:
  pie_chart:

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true
  fonts:
    - family: Circular
      fonts:
        - asset: fonts/CircularStd-Medium.ttf
        - asset: fonts/CircularAir-Light.ttf
          weight: 100
        - asset: fonts/CircularStd-Bold.ttf
          weight: 500


